//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class groue_detail
    {
        public int ID { get; set; }
        public int Groupe_thematiqeID { get; set; }
        public int UtilisateurID { get; set; }
    
        public virtual Groupe_thematiqe Groupe_thematiqe { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
