//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisitreFin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class groue_detail
    {
        public int ID { get; set; }
        public int Groupe_thematiqeID { get; set; }
        public int MembreId { get; set; }
        public string Fichier { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> datecreation { get; set; }
    
        public virtual Groupe_thematiqe Groupe_thematiqe { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
